/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData medicine = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cavity_outline = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cavity = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData doctor_patient = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData doctor = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData doctor_specialist = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData medical_kit = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData medicine_set_outline = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData medicine_set = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData medicine_pills = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData stethoscope_heart = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData stethoscope = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData tooth = const IconData(0xe80f, fontFamily: _kFontFam);
}
